ActsAsParanoid/acts_as_paranoid

lib/acts_as_paranoid.rb

Otherwise, an 'ambiguous column' error is thrown

When recovering associated records, need table name

---

README.md
lib/acts_as_paranoid.rb
lib/acts_as_paranoid/core.rb
test/test_core.rb
test/test_helper.rb

The motivation behind this pull-request is that the default behaviour of the gem with boolean columns is not very logical. Entities which have attribute `deleted == false` are currently considered deleted (because false is not nil).
When using boolean column type it is now possible to pass `allow_nulls` options which is `true` by default. When set to `false` we check for `false` values in `deleted` column instead of nils when checking if the entities are deleted or not. 
Thus it is possible to define `deleted` column as:
```ruby
t.boolean :deleted, :boolean, null: false, default: false
```
And then in the ActiveRecord model:
```ruby
acts_as_paranoid column: 'deleted', column_type: 'boolean', allow_nulls: false
```
The default behaviour is preserved and is backwards-compatible.
This new …

Added support for allow_nulls option for boolean column.

---

lib/acts_as_paranoid/core.rb

We found and issue, when `acts_as_paranoid` is used with `database_cleaner` gem and multiple database adapters like `mysql` and `postgresql`. We had the following errors
> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."deleted_at" IS NULL) LIMIT 1' at line 1: SELECT  `users`.* FROM `users` WHERE `users`.`id` = 42 AND ("users"."deleted_at" IS NULL) LIMIT 1

fix Default scope, use table connection for generating sql

---

lib/acts_as_paranoid.rb
lib/acts_as_paranoid/preloader_association.rb
test/test_helper.rb
test/test_preloader_association.rb

This fixes issue #17 by ensuring :with_deleted => true is respected when using #includes and #joins in association queries. Hat tip to @tkupari for the original fix in goncalossilva/acts_as_paranoid#115

ActiveRecord queries with includes now respect :with_deleted => true

---

README.md

Spent some time scratching my head to figure out what was happening in a project, so I decided to send this PR.
Removes mention to `.destroy!`. Adds mention to `.destroy_fully!`

Update readme for real destruction

---

test/test_validations.rb

If this test doesn't proof that the record is invalid in the first case, the validation isn't tested at all, record could be valid anyway even without destroying the objects.

Improved test_should_validate_without_deleted test, added refute

---

lib/acts_as_paranoid.rb
lib/acts_as_paranoid/core.rb

When paranoid column set as NOT NULL, recovery fail with error(e.g. "Mysql2::Error: Column 'is_del' cannot be null" ).
This PR allow set custom value with option "recovery_value" for acts_as_paranoid

allow set custom value on recover

---

lib/acts_as_paranoid/associations.rb
lib/acts_as_paranoid/preloader_association.rb

`alias_method_chain` is deprecated in favor of `prepend`. For simplicity
I've used two `alias_method` to avoid using `alias_method_chain` so
everything should be working in the same way.
Ideally would be better to use `prepend` instead of two `alias_method`, just wanted to remove the warning. Feel free to use it if you want.

Fix deprecation warning using alias_method_chain

---

test/test_core.rb
test/test_default_scopes.rb
test/test_helper.rb

Avoids all the possible -isms when dealing with humans in favor of an object that as no feelings and is generally just drawn on a page. The default scope is the minimum number of sides required for a polygon.
Props to @bad6e for finding this and @AllPurposeName for calling me out on the ableism with the prior PR. A redo of #87

Replace humans with polygons in the test

---

test/test_helper.rb

Makes test output a little cleaner.

Avoid timestamp creation deprecation messages on AR 4.2

---

README.md

Most of the code blocks in the readme already use 2 spaces for indentation, so this just updates a couple that use 4 spaces instead to be consistent.

Use two spaces for indentation

---

.travis.yml
lib/acts_as_paranoid/core.rb
test/test_associations.rb
test/test_core.rb

Notable differences in Rails 5.2:
* ActiveRecord 5.2 refuses to save deleted model instances. This means that things like `ParanoidFoo.create! deleted_at: 1.day.ago` will fail. I've decided to just drop support for this use case when Rails 5.2 is used. It also means you cannot change the time of deletion after the fact. I've changed the test that used this to stub `Time.now` instead.
* ActiveRecord 5.2 changes the implementation of `#delete` from the way it was in 4.2, 5.0, *and* 5.1. ActsAsParanoid now simply redefines it back.

Fix Rails 5.2 build

---

.gitignore
README.md
lib/acts_as_paranoid.rb
lib/acts_as_paranoid/core.rb
test/test_core.rb
test/test_helper.rb

This pull request adds an option
- `double_tap_destroys_fully: false`
that disables the behaviour of calling destroy_fully on a second destroy.
The default is true (i.e. current behaviour is retained), but in a future release a breaking change may flip that (see #92).

Double tap destroys fully

---

lib/acts_as_paranoid/core.rb
test/test_core.rb
test/test_helper.rb

Hi, we came across a problem while we were developing our software which was that counter cache columns weren't being decremented when deleting an associated object and they were also not being increment when recovering an associated object. I think I managed it pretty well with help from pull request #40  .

Support for incrementing and decrementing counter cache columns on associated objects for ActiveRecord>=4.x

---

lib/acts_as_paranoid/core.rb

Version 4.2 or higher of ActiveRecord is required, so no need to check for versions of 4 or higher.

Remove superflous version check

---

lib/acts_as_paranoid/core.rb
test/test_core.rb
test/test_helper.rb

This change fixes two issues with using counter caches. One is related to being able to specify a custom counter cache column, and the other is using a counter cache on an optional belongs_to association.

Fix a couple issues with counter caches

---

lib/acts_as_paranoid.rb
test/test_core.rb
test/test_helper.rb

I originally opened #117  without tests, and since then have deleted my fork, so reforked and opened this PR with a spec @mvz 
Thought about also asserting that `ParanoidWithExplicitTableNameAfterMacro.only_deleted` is working since that's how I found the error, but I think this test is clearer what exactly we're testing. Lemme know what ya think
* paranoid_column_reference is currently a class attribute which is set
when a class is loaded and the acts_as_paranoid method is invoked. A
rails model can set its table_name after it declares itself as
acts_as_paranoid. This means that whenever paranoid_column_reference is
referenced in the gem it does not match the table_name for the model
which can cause errors.
* e.g. ActsAsParanoid::Core#only_deleted references
`paranoid_column_reference` …

Allow model to set table_name after acts_as_paranoid macro

---

lib/acts_as_paranoid/core.rb
test/test_core.rb

Currently all records respond to the `.recover` method, including
records that are not deleted. This change ensures that calling `recover`
on un-deleted records will no-op. We also added specs to verify this
behavior.
Co-authored-by: Valerie Woolard <valerie.woolard@gmail.com>

Adds guard clause to prevent recovery of non-deleted records

---

lib/acts_as_paranoid/core.rb
test/test_core.rb

Fix a record being dirty after destroying it

---

README.md
lib/acts_as_paranoid/core.rb
test/test_core.rb

* Add `recover!` method which raises error if the recovery fails
* Add tests and docs for `recover!`
* Add new section `callbacks` to Readme.md to document about the callbacks
NOTE: The test for `recover!` fails for Rails 5 for the same reason as #71

Recover! method

---

lib/acts_as_paranoid/core.rb
test/test_core.rb

Part of #108, fixing the following issue:
> There is no way to know if a record was soft deleted or hard deleted in a destroy callback.
destroyed?/deleted? returns true iff an object is deleted (soft or hard).
destroyed_fully?/deleted_fully? returns true iff an object is deleted from the database (hard destroy).

Add predicate to check if record was soft deleted or hard deleted

---

.travis.yml
README.md

* Drop support for Ruby 2.3 and below, since they are unmaintained
* Add Ruby 2.7 to the build matrix

Update set of supported rubies to 2.4-2.7

---

.gitignore
acts_as_paranoid.gemspec
lib/acts_as_paranoid.rb
test/test_helper.rb

- Add simplecov dependency
- Make sure acts_as_paranoid is loaded after SimpleCov.start by not loading everything through Bundler.require
- Activate branche coverage
- Ignore coverage output

Add SimpleCov

---

test/test_associations.rb
test/test_helper.rb

This silences warnings we can do something about. Ruby 2.6 running the tests should be warning-free. For 2.7, we have to wait for new Rails releases.

Silence warnings

---

Gemfile
Rakefile

* Guards against the common mistake of running the `test:active_record_*` tasks with `bundle exec`
* Makes running `bundle exec rake test` work

Improve dev experience

---

lib/acts_as_paranoid/validations.rb

Instead of re-implementing all of `#validate_each`, just extend the `#build_relation` method by adding the paranoid scope.

Simplify validation override

---

lib/acts_as_paranoid/core.rb

When using the hash form, unscope expects a symbol as the value. The previous version seems to have only worked accidentally.

Use correct unscope syntax so unscope works on Rails Edge

---

lib/acts_as_paranoid/associations.rb

Fixes the ruby 2.7 deprecation warning emitted by acts_as_paranoid:
`lib/acts_as_paranoid/associations.rb:42: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

Fix ruby 2.7 keyword argument deprecation warning

---

README.md

When I tried to  add `gem 'acts_as_paranoid', '~> 0.7.0'` to my `Gemfile`, it gave me: 
`Could not find gem 'acts_as_paranoid (~> 0.7.0)' in any of the gem sources listed in your Gemfile.`
After looking into it further, it looks like the latest version is only 0.6.3 in rubygems.org:
https://rubygems.org/gems/acts_as_paranoid

Updates version number instructions for installing gem

---

.rubocop.yml
acts_as_paranoid.gemspec

Updates RuboCop to 0.89.1, and fixes Gemspec/RequiredRubyVersion offense by making current lowest supported Ruby version (2.4) explicit.

Update RuboCop/specify Ruby version

---

acts_as_paranoid.gemspec

Simplecov 0.19 is available; Update the development dependencies to allow its use. Also allow 0.18.1 for running the specs on Ruby 2.4, which is not supported by 0.19.

Loosen dependency on simplecov

---

lib/acts_as_paranoid.rb
test/test_core.rb

Thank you for providing such a great gem.
I created this PR because I ran into one problem while using this gem in my project.
In case of `column type:" boolean "` and `allow nulls: false`, `nil` should not be stored in the `deleted` column.
However, when the `recover` and` recover!` methods are used for the object of the class with the following conditions,` nil` is stored in the `deleted` column.
```
class ParanoidBooleanNotNullable < ActiveRecord::Base
acts_as_paranoid column: "deleted", column_type: "boolean", allow_nulls: false
end
ParanoidBooleanNotNullable.create!
ParanoidBooleanNotNullable.first.destroy
ParanoidBooleanNotNullable.delete_flag # => true
ParanoidBooleanNotNullable.only_deleted.first.recover # => true
ParanoidBooleanNotNullable.delete_flag # => nil 'expected is false' …
```

Fixed Inconsistency in `column_type`,` allow_nulls`, `recovery_value`

---

.rubocop.yml
.rubocop_todo.yml
lib/acts_as_paranoid/core.rb
test/test_core.rb

The scopes `deleted_after_time` and `deleted_before_time` lacked code to remove the default scope to non-deleted items.
Fixes #42.

Test and fix deletion time scopes

---

test/test_helper.rb
test/test_validations.rb

Closes #43. This issue was probably fixed by #85. The present pull request adds tests to demonstrate that validation behaves correctly with serialized attributes.

Test uniqueness validation without deleted with serialized attributes

---

.gitignore
test/test_helper.rb

This removes an old leftover hack that set the logger to an anonymous StringIO object (introduced to solve an issue on Ruby 1.8!). Instead, ActiveRecord logging is set up to log to log/test.log.

Log ActiveRecord activity to a visible log during tests

---

.rubocop_todo.yml
lib/acts_as_paranoid/core.rb

For a `belongs_to` association where the foreign key is nil, the existing code would create a scope on the assoicated table with a where clause selecting `id IS NULL`. This would always fail to find any records, but it's better to not perform the query at all.

Avoid querying nil belongs_to associations when recovering

---

.rubocop.yml
test/test_default_scopes.rb
test/test_helper.rb
test/test_relations.rb

The existing test setup created tables for all models used during the tests. This is excessive. This pull requests starts the process of splitting up the database setup code so fewer tables are created and model definitions are more localized.

Start test setup simplification

---

.rubocop_todo.yml
lib/acts_as_paranoid/relation.rb
test/test_relations.rb

On single records, `destroy!` was already replaced with `destroy_fully!` before. This change does the same for relations. This reduces surprising behavior when compared to standard ActiveRecord.
`destroy!` is kept for now with a deprecation message.
See #82.

Replace `destroy!` with `destroy_fully!` on relations

---

.rubocop.yml
lib/acts_as_paranoid.rb
lib/acts_as_paranoid/core.rb
test/test_deprecated_behavior.rb

The `recovery_value` setting was introduced in #60 for use with non-null booleans, but since there's only one sensible option for that case there is no point in making it a setting.
Final removal of this setting as a breaking change in a way, although this setting was never documented. Therefore, using this setting will still work for now and give a deprecation warning.
Closes #72.

Calculate recovery_value instead of using a setting

---

test/test_associations.rb

Assigning to the paranoid column is no longer supported: Rails does not support creating a model in a deleted state.

Update test of mass assignment to paranoid column

---

.rubocop.yml
.rubocop_todo.yml
acts_as_paranoid.gemspec
test/test_associations.rb
test/test_core.rb
test/test_helper.rb
test/test_validations.rb

- Add rubocop-minitest, using version 0.11.x so Ruby 2.4 is supported
- Autocorrect several offenses
- Remove home-grown assert_empty implementation
- Regenerate RuboCop to-do file to silence warnings that need more work

Introduce rubocop-minitest

---

lib/acts_as_paranoid/core.rb
test/test_core.rb

No need to stale paranoid_value when destroying fully

---

lib/acts_as_paranoid/core.rb

These methods should only be used by ActsAsParanoid internally.

Make helper methods for dependent associations private

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
acts_as_paranoid.gemspec

Ruby 2.4 has been EOL for quite some time.

Drop support for Ruby 2.4

---

.github/workflows/ruby.yml
acts_as_paranoid.gemspec
gemfiles/active_record_70.gemfile

Rails 7.0.0 is already launch, I update the gemspec and active record dependencies in gemfiles. Hope it helps, 
tested in my local environment
gemfile: 
`gem 'acts_as_paranoid',               '~> 0.7.3', git: 'https://github.com/cloudsbird/acts_as_paranoid', branch: 'rails_7_support'`
ruby: 3.0.0
rails: 7.0.0

update to support rails 7

---

lib/acts_as_paranoid.rb
lib/acts_as_paranoid/association_reflection.rb
lib/acts_as_paranoid/associations.rb
test/test_associations.rb

The override of `belongs_to` creates a scope in the association where normally there would be none if the `:with_deleted` option is given. Having a scope in an association makes ActiveRecord refuse to automatically find an inverse relation. This change adds an override to make an exception if the scope was only added to support the `:with_deleted` option.
Fixes #232.

Fix association building for belongs_to with :with_deleted option

---

.rubocop.yml
acts_as_paranoid.gemspec

- Bump minimum RuboCop version
- Configure Layout/LineContinuationLeadingSpace

Update RuboCop and its configuration

---

.github/workflows/ruby.yml
Appraisals
gemfiles/active_record_61.gemfile
gemfiles/active_record_70.gemfile

- Add JRuby 9.4 to the test matrix
- Update activerecord-jdbcsqlite3-adapter versions

Support JRuby 9.4

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
acts_as_paranoid.gemspec

- Drop support for Ruby 2.6
- Update support information in README

Drop support for Ruby 2.6

---

.rubocop.yml
acts_as_paranoid.gemspec

- Bump rubocop version
- Require development dependencies to be in the gemspec

Bump RuboCop dependency version and update configuration

---

.github/workflows/ruby.yml
.rubocop.yml
acts_as_paranoid.gemspec

- Drop support for Ruby 2.7
- Build with Rubies 3.0 through 3.3 in CI

Support Ruby 3.0 and up

---

Gemfile
gemfiles/active_record_61.gemfile
gemfiles/active_record_70.gemfile
gemfiles/active_record_71.gemfile

We do not specify the exact `sqlite3` version in the Gemfiles. Recently, the `sqlite3` v2 was released, but rails wants `~> 1.4`.

Use correct sqlite3 versions in tests

---

lib/acts_as_paranoid.rb

The problem is well described in https://github.com/rails/rails/issues/46567.
We are currently hitting this when upgrading to rails 7.2.

Do not load `ActiveRecord` too early

---

acts_as_paranoid.gemspec

Supported here: https://guides.rubygems.org/specification-reference/#metadata  Useful for running https://github.com/MaximeD/gem_updater

Add changelog_uri to gemspec

---

acts_as_paranoid.gemspec

Using add_runtime_dependency is soft-deprecated and now flagged by RuboCop.

Replace soft-deprecated runtime dependency specification

---

CONTRIBUTING.md

A half-baked pull request is often much less useful than a good bug report. Therefore, this change encourages contributors to open an issue instead of submitting an unfinished pull request.
Also, stress that pull requests may be refused in the end.

Improve contribution instructions

---

Appraisals
Gemfile
gemfiles/active_record_71.gemfile
gemfiles/active_record_72.gemfile

Allow version 2.0 for the sqlite3 gem for testing with Rails 7.2

Loosen sqlite3 development dependency

---

.github/workflows/ruby.yml
Appraisals
Gemfile
acts_as_paranoid.gemspec
gemfiles/active_record_71.gemfile
gemfiles/active_record_80.gemfile

This change updates acts_as_paranoid's dependencies to allow activerecord and activesupport version 8.0.
No functional changes are needed.
- Update acts_as_paranoid's dependencies on activerecord and activesupport to allow version 8.0
- Remove activerecord-jdbcsqlite3-adapter dependency to allow Bundler to consider activerecord 8.0
- Add an appraisal for activerecord 8.0
- Update GitHub Actions configuration to test with the new active_record_80 appraisal

Support Rails 8.0

---

test/test_helper.rb

This can be removed once Rails 7.0 support is dropped.
See https://github.com/rails/rails/issues/54260

Add workaround in tests for concurrent-ruby no longer loading logger

---

.github/workflows/ruby.yml
.rubocop.yml
acts_as_paranoid.gemspec

This drops support for Ruby 3.0 which is EOL.

Support Ruby 3.1 through 3.4
