ActsAsParanoid/acts_as_paranoid

- lib/acts_as_paranoid/core.rb
- test/test_core.rb
- test/test_helper.rb
> Try to fix decrement_counters

- .travis.yml
- Rakefile
- acts_as_paranoid.gemspec
- gemfiles/active_record_50.gemfile
- lib/acts_as_paranoid.rb
- lib/acts_as_paranoid/core.rb
- lib/acts_as_paranoid/validations.rb
- test/test_helper.rb
Full compatibility with Rails 5
> Compatibility with Rails 5

- README.md
Although the default name and type seem obvious, it took me a minute to find where the readme actually says this. Hope this makes the readme a little better for everyone.
> updating readme for better clarity

- .travis.yml
- Rakefile
- gemfiles/active_record_42.gemfile
- gemfiles/active_record_50.gemfile
- gemfiles/active_record_51.gemfile
- gemfiles/active_record_52.gemfile
- gemfiles/active_record_edge.gemfile
Extends #99.
* Add Rails 5.2 target
* Build on Ruby 2.5
* Only build with Rails edge on 2.4.1+
* Improve the JRuby build
> Improve build target set

- .travis.yml
- Rakefile
- gemfiles/active_record_52.gemfile
> Add active_record 5.2 build

- lib/acts_as_paranoid/associations.rb
- lib/acts_as_paranoid/preloader_association.rb
Fix for #94 . I'm not sure if there is a better way to approach this.
> Make compatible with rails 5.2.0.rc1

- .travis.yml
- acts_as_paranoid.gemspec
- gemfiles/active_record_42.gemfile
- gemfiles/active_record_50.gemfile
There are quite a few build failures due to version incompatibilities. This pull request tries to fix them.
> Fix build issues

- acts_as_paranoid.gemspec
- test/test_associations.rb
- test/test_helper.rb
Tests belongs_to associations with and with `with_deleted: true` more directly.
> Add more association tests

- .travis.yml
- gemfiles/active_record_60.gemfile
* Ensure tests are run against Edge Rails
* Use default Bundler
* Fix JRuby builds and require them to succeed
> Update Travis CI configuration

- README.md
- test/test_core.rb
> Document save after destroy behavior

- README.md
> Adding example with destroyed_fully? and deleted_fully? to the readme.

- test/test_helper.rb
See https://github.com/jruby/jruby/issues/6547 and https://github.com/ruby-i18n/i18n/issues/555
> Add workaround for test failures on JRuby with I18n 1.8.9

- test/test_helper.rb
- test/test_relations.rb
> Demonstrate fake removal through relation on non-paranoid model

- test/test_core.rb
This checks that #46 stays fixed.
> Add tests for scope chaining

- lib/acts_as_paranoid/core.rb
- test/test_core.rb
> Reload has_one associations after dependent recovery

- lib/acts_as_paranoid/core.rb
- test/test_dependent_recovery.rb
> Make dependent recovery work when parent is non-optional

- test/test_table_namespace.rb
This was fixed by #131.
Closes #98.
> Demonstrate that namespaced models and tables work

- .rubocop.yml
- .rubocop_todo.yml
- lib/acts_as_paranoid/core.rb
- test/test_core.rb
- test/test_helper.rb
This PR is to address the issue mentioned here https://github.com/ActsAsParanoid/acts_as_paranoid/issues/221
> Raise ActiveRecord::RecordNotDestroyed if destroy returns false

- lib/acts_as_paranoid/core.rb
- test/test_core.rb
- test/test_default_scopes.rb
> Make with_deleted not unscope only_deleted

- Manifest.txt
- Rakefile
- acts_as_paranoid.gemspec
- Remove obsolete install task
- Improve gemspec formatting
- Update development dependencies
- Remove test files from the gem
- Use a manifest file to track gem contents
> Improve gemspec

- .rubocop.yml
- acts_as_paranoid.gemspec
- lib/acts_as_paranoid.rb
- lib/acts_as_paranoid/core.rb
- Add more RuboCop plugins
- Fix Performance/RedundantMerge offense
- Fix Performance/CollectionLiteralInLoop offense
> Add more RuboCop plugins and fix new offenses

- .github/workflows/ruby.yml
This action supports caching with different gemfiles out of the box.
See https://github.com/ruby/setup-ruby#matrix-of-gemfiles.
> Use ruby-setup's native caching

- acts_as_paranoid.gemspec
Straight irb is now good enough for debugging.
> Remove dependency on pry
